src/Service.Host/client/src/middleware/itemCreated.js
src/Service.Host/client/src/middleware/itemCreated.test.js

fixes #69, adds tests to stop regression

---

src/Facade/Facade.csproj

update linn.common.reporting.resources to fix csv ordering.

---

src/Service/Modules/CitsModule.cs
tests/Integration/Service.Tests/CitsModuleSpecs/ContextBase.cs
tests/Integration/Service.Tests/CitsModuleSpecs/WhenGettingCits.cs

Realised that Lewis has a pr in with the module named as CitsModule - I just merged one called CitModule. Doing this PR to stop duplicate modules being checked in by accident.

update cits module name

---

src/Persistence.LinnApps/Repositories/ManufacturingRoutesRepository.cs
src/Persistence.LinnApps/Repositories/PartsRepository.cs
src/Persistence.LinnApps/Repositories/ProductionTriggerLevelsRepository.cs

service is referencing unimplemented repository method

---

src/Domain.LinnApps/Common/AuthorisationService.cs
src/Domain.LinnApps/Common/IAuthorisationService.cs
src/Domain.LinnApps/Triggers/PtlSettings.cs
src/Facade/Common/ISingleRecordFacadeService.cs
src/Facade/Common/SingleRecordFacadeService.cs
src/Facade/ResourceBuilders/OsrInfoResourceBuilder.cs
src/Facade/ResourceBuilders/PtlSettingsResourceBuilder.cs
src/Facade/Services/ProductionTriggerLevelService.cs
src/Facade/Services/PtlSettingsFacadeService.cs
src/IoC/PersistenceModule.cs
src/IoC/ResponsesModule.cs
src/IoC/ServiceModule.cs
src/Persistence.LinnApps/Repositories/IMasterRepository.cs
src/Persistence.LinnApps/Repositories/OsrRunMasterRepository.cs
src/Persistence.LinnApps/Repositories/PtlSettingsRepository.cs
src/Persistence.LinnApps/ServiceDbContext.cs
src/Resources/PtlSettingsResource.cs
src/Service/Modules/ProductionTriggerLevelsModule.cs
src/Service/ResponseProcessors/PtlSettingsResponseProcessor.cs
tests/Integration/Service.Tests/ProductionTriggerLevelsModuleSpecs/ContextBase.cs
tests/Integration/Service.Tests/ProductionTriggerLevelsModuleSpecs/WhenGettingSettings.cs
tests/Unit/Facade.Tests/PtlSettingsFacadeServiceSpecs/ContextBase.cs
tests/Unit/Facade.Tests/PtlSettingsFacadeServiceSpecs/WhenUpdating.cs

add PtlSettings.
add SingleRecordFacadeService.
add example ResponseProcessor with claims

bring across some of the AuthorisationService stuff.

---

src/Facade/ResourceBuilders/WorksOrderDetailsResourceBuilder.cs
src/Facade/ResourceBuilders/WorksOrderResourceBuilder.cs
src/Facade/Services/WorksOrdersService.cs
src/Service.Host/client/src/components/App.js
src/Service.Host/client/src/components/NotFound.js
src/Service.Host/client/src/components/Root.js
src/Service.Host/client/src/components/reports/OutstandingWorksOrdersReport.js
src/Service.Host/client/src/components/reports/OutstandingWorksOrdersReportOptions.js
src/Service.Host/client/src/itemTypes.js
src/Service.Host/client/src/reportTypes.js
src/Service/Modules/WorksOrdersModule.cs
tests/Integration/Service.Tests/WorksOrdersModuleSpecs/WhenAddingAWorksOrder.cs
tests/Integration/Service.Tests/WorksOrdersModuleSpecs/WhenCancellingAWorksOrder.cs
tests/Integration/Service.Tests/WorksOrdersModuleSpecs/WhenGettingAll.cs
tests/Integration/Service.Tests/WorksOrdersModuleSpecs/WhenGettingOutstandingWorksOrdersReport.cs
tests/Integration/Service.Tests/WorksOrdersModuleSpecs/WhenGettingOutstandingWorksOrdersReportCsv.cs
tests/Integration/Service.Tests/WorksOrdersModuleSpecs/WhenGettingOutstandingWorksOrdersReportWithSearchParameters.cs
tests/Integration/Service.Tests/WorksOrdersModuleSpecs/WhenGettingWorksOrderByOrderNumber.cs
tests/Integration/Service.Tests/WorksOrdersModuleSpecs/WhenGettingWorksOrderDetails.cs
tests/Integration/Service.Tests/WorksOrdersModuleSpecs/WhenSearchingByOrderNumber.cs
tests/Unit/Facade.Tests/WorksOrderServiceSpecs/WhenCancellingWorksOrder.cs
tests/Unit/Facade.Tests/WorksOrderServiceSpecs/WhenCancellingWorksOrderWithInvalidParameters.cs
tests/Unit/Facade.Tests/WorksOrderServiceSpecs/WhenCreatingWorksOrder.cs
tests/Unit/Facade.Tests/WorksOrderServiceSpecs/WhenCreatingWorksOrderWithInvalidResource.cs
tests/Unit/Facade.Tests/WorksOrderServiceSpecs/WhenUpdatingAndWorksOrderNotFound.cs
tests/Unit/Facade.Tests/WorksOrderServiceSpecs/WhenUpdatingWorksOrder.cs

Change works orders routes to use `/production/works-orders` 
Add auth to create and add routes

Works Orders route update

---

src/Domain.LinnApps/AuthorisedAction.cs
src/Facade/ResourceBuilders/PtlSettingsResourceBuilder.cs
src/IoC/ServiceModule.cs
src/Service.Host/client/src/actions/index.js
src/Service.Host/client/src/actions/ptlSettingsActions.js
src/Service.Host/client/src/components/App.js
src/Service.Host/client/src/components/Root.js
src/Service.Host/client/src/components/productionTriggerLevels/PtlSettings.js
src/Service.Host/client/src/containers/productionTriggerLevels/PtlSettings.js
src/Service.Host/client/src/itemTypes.js
src/Service.Host/client/src/reducers/index.js
src/Service.Host/client/src/reducers/ptlSettings.js
src/Service.Host/client/src/selectors/ptlSettingsSelectors.js
src/Service/Modules/ProductionTriggerLevelsModule.cs
tests/Integration/Service.Tests/ProductionTriggerLevelsModuleSpecs/ContextBase.cs
tests/Integration/Service.Tests/ProductionTriggerLevelsModuleSpecs/WhenUpdatingSettings.cs
tests/Unit/Facade.Tests/ResourceBuilders/PtlSettingsSpecs/ContextBase.cs
tests/Unit/Facade.Tests/ResourceBuilders/PtlSettingsSpecs/WhenBuildingWithStartTriggerRunPermission.cs
tests/Unit/Facade.Tests/ResourceBuilders/PtlSettingsSpecs/WhenBuildingWithUpdatePermission.cs
tests/Unit/Facade.Tests/ResourceBuilders/PtlSettingsSpecs/WhenBuildingWithoutPermissions.cs

ptl settings form with authorisation

Ptl settings

---

src/Domain.LinnApps/AccountingCompany.cs
src/Domain.LinnApps/BackOrders/ProductionBackOrder.cs
src/Domain.LinnApps/Triggers/ProductionTriggerFacts.cs
src/Facade/ResourceBuilders/ProductionBackOrderResourceBuilder.cs
src/Facade/ResourceBuilders/ProductionTriggersFactsResourceBuilder.cs
src/Facade/Services/ProductionTriggersFacadeService.cs
src/IoC/PersistenceModule.cs
src/Persistence.LinnApps/Repositories/AccountingCompanyRepository.cs
src/Persistence.LinnApps/Repositories/ProductionBackOrderQueryRepository.cs
src/Persistence.LinnApps/ServiceDbContext.cs
src/Resources/ProductionBackOrderResource.cs
src/Resources/ProductionTriggerFactsResource.cs
tests/Integration/Service.Tests/ProductionTriggersModuleSpecs/WhenGettingProductionTriggerFacts.cs
tests/Unit/Facade.Tests/ProductionTriggersFacadeServiceSpecs/ContextBase.cs
tests/Unit/Facade.Tests/ProductionTriggersFacadeServiceSpecs/WhenGettingTriggerFactsWithBackOrders.cs

production back orders are needed for trigger facts and will also be needed in OSR production back order report

production back orders added into facts

---

src/Service.Host/client/src/components/serialNumberReissue/SerialNumberReissue.js
src/Service.Host/client/src/components/worksOrders/WorksOrder.js
src/Service.Host/client/src/containers/serialNumberReissue/SerialNumberReissue.js
src/Service.Host/client/src/containers/worksOrders/CreateWorksOrder.js
src/Service.Host/client/src/containers/worksOrders/WorksOrder.js
src/Service.Host/client/src/reducers/index.js
src/Service.Host/package-lock.json
src/Service.Host/package.json

Sernos reissue search fix

---

aws/application.yml

I've increased memory to 250 as this is what we're using in products-maint - does this seem like a reasonable number?
I've also removed the optional cpu values which may have been incorrect.

AWS yaml memory increase

---

src/Service.Host/package-lock.json
src/Service/Modules/WorksOrdersModule.cs

hopefully fix for works order batch notes route

---

src/Service/Modules/HomeModule.cs

need to make pr to test in sys

different creates for the different routes within production

---

src/Domain.LinnApps/BoardTests/BoardTestReports.cs
tests/Unit/Domain.Tests/BoardTestReportsSpecs/WhenGettingReportWithSerialNumber.cs

(Also added indexes to the database)

make board test report more efficient. 

---

src/Service.Host/client/src/components/__tests__/WorksOrder.test.js
src/Service.Host/client/src/components/serialNumberReissue/SerialNumberReissue.js
src/Service.Host/client/src/components/worksOrders/WorksOrder.js
src/Service.Host/client/src/components/worksOrders/WorksOrderSerialNumbers.js
src/Service.Host/client/src/containers/assemblyFails/AssemblyFail.js
src/Service.Host/client/src/containers/serialNumberReissue/SerialNumberReissue.js
src/Service.Host/client/src/containers/worksOrders/WorksOrder.js

- Add table to view serial numbers associated with a works order
- Issue Serial Number takes a query string to search sernos on mount
- Link to Issue Sernos from works order serial numbers

Works Order serial numbers view

---

src/Service.Host/client/src/components/reports/AteStatusReportOptions.js

tiny tweak so I can let people test this.

set default start date to start of a week

---

src/Service.Host/client/assets/printStyles.css
src/Service.Host/client/src/components/reports/ProductionBackOrdersReport.js
src/Service.Host/package-lock.json

Zoomed in printing of production back orders report for liz

---

src/Domain.LinnApps/Part.cs
src/Domain.LinnApps/PartFailLog.cs
src/Domain.LinnApps/Reports/PartsReportService.cs
src/Persistence.LinnApps/Repositories/PartFailLogRepository.cs
src/Persistence.LinnApps/ServiceDbContext.cs
src/Service.Host/package-lock.json
tests/Unit/Domain.Tests/PartsReportSpecs/ContextBase.cs
tests/Unit/Domain.Tests/PartsReportSpecs/WhenGettingPartFailDetailsReport.cs

Add part description to part fail detail report and sort by date

---

src/Service.Host/client/src/components/reports/measures/ProductionMeasuresCitTable.js

plug in drill down

---

src/Service.Host/client/src/components/labelReprints/LabelReprint.js

incase first time didn't work
http://rndsupport.linn.co.uk/scp/tickets.php?id=12262

reprint tweaks - change save to print and let them hit print again

---

src/Persistence.LinnApps/Repositories/OsrRunMasterRepository.cs
src/Persistence.LinnApps/Repositories/PtlMasterRepository.cs
src/Persistence.LinnApps/ServiceDbContext.cs

use single record repo for master tables.

---

src/Domain.LinnApps/Reports/ProductionMeasuresReportService.cs
src/Domain.LinnApps/Services/PurchaseOrderDomainService.cs
src/Domain.LinnApps/Triggers/ProductionTrigger.cs
src/Domain.LinnApps/Triggers/ProductionTriggersReport.cs
src/Facade/Extensions/EnumExtensions.cs
src/Facade/ResourceBuilders/BuildPlanDetailResourceBuilder.cs
src/Facade/ResourceBuilders/BuildPlanRuleResourceBuilder.cs
src/Facade/ResourceBuilders/LabelPrintResourceBuilder.cs
src/Facade/ResourceBuilders/LabelPrintResponseResourceBuilder.cs
src/Facade/ResourceBuilders/LabelTypeResourceBuilder.cs
src/Facade/ResourceBuilders/StoragePlaceResourceBuilder.cs
src/Facade/Services/BuildPlanDetailService.cs
src/Facade/Services/BuildPlanService.cs
src/Facade/Services/PartsReportFacadeService.cs
src/IoC/ServiceModule.cs
src/Persistence.LinnApps/Persistence.LinnApps.csproj
src/Proxy/Proxy.csproj
src/Service.Host/Service.Host.csproj
src/Service.Host/package-lock.json
src/Service/Modules/BuiltThisWeekModule.cs
src/Service/Modules/ProductionTriggerLevelsModule.cs
src/Service/Modules/ShortageModule.cs
src/Service/ResponseProcessors/BuildPlanDetailResponseProcessor.cs
src/Service/ResponseProcessors/IdAndNameResponseProcessor.cs
tests/Integration/Service.Tests/Service.Tests.csproj
tests/Unit/Domain.Tests/Domain.Tests.csproj
tests/Unit/Facade.Tests/Facade.Tests.csproj
tests/Unit/Messaging.Tests/Messaging.Tests.csproj
tests/Unit/Proxy.Tests/Proxy.Tests.csproj

and remove unnecessary authentication from production triggers.

Nuget updates

---

src/Service.Host/client/src/components/__tests__/labelPrint.tests.js
src/Service.Host/client/src/components/__tests__/manufacturingResource.test.js
src/Service.Host/client/src/components/labelPrinting/LabelPrint.js
src/Service.Host/client/src/components/manufacturingResources/ManufacturingResource.js

mfg resources - make cost & description not required

---

src/Service.Host/client/assets/printStyles.css
src/Service.Host/client/src/components/reports/ProductionBackOrdersReport.js
src/Service.Host/package-lock.json
src/Service.Host/package.json

for liz in ticket http://rndsupport.linn.co.uk/scp/tickets.php?id=12113 last reply. Needs npm install done after shared components change goes through

used new optional allow page break style in report table in production back orders

---

src/Service.Host/client/src/components/productionTriggerLevels/TriggerLevels.js

Build plans wasn't implemented yet before so button was added without live link

Uncomment link while I remember

---

src/Service.Host/client/src/components/ate/AteTest.js
src/Service.Host/client/src/components/mWTimings/TimingsReport.js
src/Service.Host/client/src/containers/mWTimings/TimingsReport.js

- hopefully prevents against fails ending up on the wrong report

More fixes

---

src/Facade/Services/WorksOrdersService.cs
src/Service.Host/client/src/components/__tests__/WorksOrder.test.js
src/Service.Host/client/src/components/reports/PartFailDetailsReport.js
src/Service.Host/client/src/components/worksOrders/WorksOrder.js
src/Service.Host/client/src/containers/worksOrders/WorksOrder.js
tests/Unit/Facade.Tests/WorksOrderServiceSpecs/WhenCancellingWorksOrder.cs

- allow choice of cancelledBy as opposed to just using current user
- move print buttons to top
- more clear cancelaltion process, opens in modal

Works order ut marks fixes

---

src/Service.Host/client/src/components/worksOrders/WorksOrder.js
src/Service.Host/client/src/containers/worksOrders/WorksOrder.js

- addresses #328 
- takes users back to external urls if that's where they came from :)
- I'll probably write a selector and move the event handler into the shared components at some point, but want to check it works in practise

use window history api when user came from another app

---

src/Service.Host/client/src/components/productionTriggerLevels/TriggerLevels.js

http://rndsupport.linn.co.uk/scp/tickets.php?id=12430

add kanban size to trigger levels search results for alisons ticket

---

src/Service.Host/client/src/components/buildsbyDepartment/BuildsSummaryReportOptions.js

remove extraneous toIsoString call

---

src/Service.Host/client/src/helpers/userManager.js

This seems to be working correctly after restarting the project and browser a few times. I'm not sure why I was having problems with this yesterday but seems good now.

fix redux-oidc sign out redirect on dev

---

src/Service.Host/client/src/components/productionTriggerLevels/TriggerLevels.js

workstation search initialisation corrected 

---

src/Domain.LinnApps/Reports/ShortageSummaryReportService.cs

Was causing the report to fail this morning - fixes Stevie's ticket

deduplicate parts in shortages report details

---

src/Domain.LinnApps/AuthorisedAction.cs
src/Facade/ResourceBuilders/ProductionTriggerLevelResourceBuilder.cs
src/Service.Host/client/src/components/productionTriggerLevels/TriggerLevel.js
src/Service.Host/package-lock.json

http://rndsupport.linn.co.uk/scp/tickets.php?id=13331

added new permission to allow updating of ptl description field 

---

src/Domain.LinnApps/Reports/IProductionMeasuresReportService.cs
src/Domain.LinnApps/Reports/ProductionMeasuresReportService.cs
src/Facade/Services/IProductionMeasuresReportFacade.cs
src/Facade/Services/ProductionMeasuresReportFacade.cs
src/Resources/RequestResources/FailedPartsReportOptionsResource.cs
src/Service.Host/client/src/components/reports/FailedPartsReport.js
src/Service.Host/client/src/containers/reports/FailedPartsReport.js
src/Service/Modules/ProductionMeasuresModule.cs
tests/Integration/Service.Tests/ProductionMeasuresModuleSpecs/WhenGettingFailedPartsReport.cs
tests/Unit/Domain.Tests/ProductionMeasuresReportServiceSpecs/WhenGettingReportForAllCits.cs
tests/Unit/Domain.Tests/ProductionMeasuresReportServiceSpecs/WhenGettingReportForCit.cs
tests/Unit/Facade.Tests/ProductionMeasuresFacadeServiceSpecs/WhenGettingPartFailDetailsReport.cs

- haven't written any new tests yet since I'm not 100% sure this is what is being asked for. Will write tests in a seperate pr once I have the OK from Stephen
- I tried to keep it as flexible as possible, so you can now order by date asc or desc, or order by part number, or filter part numbers using an asterisk wildcard

Failed parts report options

---

src/Domain.LinnApps/Reports/IProductionMeasuresReportService.cs
src/Domain.LinnApps/Reports/ProductionMeasuresReportService.cs
src/Domain.LinnApps/ViewModels/FailedParts.cs
src/Facade/Services/IProductionMeasuresReportFacade.cs
src/Facade/Services/ProductionMeasuresReportFacade.cs
src/Persistence.LinnApps/ServiceDbContext.cs
src/Resources/RequestResources/FailedPartsReportOptionsResource.cs
src/Service.Host/client/src/components/reports/FailedPartsReport.js
src/Service/Modules/ProductionMeasuresModule.cs
tests/Integration/Service.Tests/ProductionMeasuresModuleSpecs/WhenGettingFailedPartsReport.cs
tests/Unit/Domain.Tests/ProductionMeasuresReportServiceSpecs/WhenGettingFailedPartsReportAndOrderingByDateAsc.cs
tests/Unit/Domain.Tests/ProductionMeasuresReportServiceSpecs/WhenGettingFailedPartsReportAndOrderingByDateDesc.cs
tests/Unit/Domain.Tests/ProductionMeasuresReportServiceSpecs/WhenGettingFailedPartsReportForAPart.cs
tests/Unit/Domain.Tests/ProductionMeasuresReportServiceSpecs/WhenGettingFailedPartsReportForPartsWithWildcard.cs
tests/Unit/Domain.Tests/ProductionMeasuresReportServiceSpecs/WhenGettingReportForAllCits.cs
tests/Unit/Domain.Tests/ProductionMeasuresReportServiceSpecs/WhenGettingReportForCit.cs
tests/Unit/Facade.Tests/ProductionMeasuresFacadeServiceSpecs/WhenGettingPartFailDetailsReport.cs

- allows filtering by Linn Produced and Vendor Manager

Ticket 15307

---

src/Facade/ResourceBuilders/ProductionTriggerSummaryResourceBuilder.cs
src/Resources/ProductionTriggerSummaryResource.cs
src/Service.Host/client/src/components/reports/triggers/TriggersList.js

http://rndsupport.linn.co.uk/scp/tickets.php?id=15506

add override trigger level to trigger report

---

src/Proxy/WorksOrderLabelPack.cs
src/Service.Host/client/src/components/worksOrders/WorksOrder.js
src/Service.Host/package-lock.json

is this right??
Didn't seem that the printer group could ever change. 
Not sure the local storage works for me either but not worried about that right now.

allow setting of printer group to Clear

---

src/Domain.LinnApps/Measures/PartFail.cs
src/Resources/PartFailResource.cs
src/Service.Host/client/src/components/partFails/PartFail.js

for ticket 17169 for mark to allow setting of 0.5 in part fail log even though it never allowed it before

ability to input half pairs

---

src/Domain.LinnApps/Reports/PartsReportService.cs
tests/Unit/Domain.Tests/PartsReportSpecs/WhenGettingPartFailDetailsReportWithCost.cs

there might be a better way to show 0.5 as 0.5 not 1 rather than converting it to a text field

to make 0.5 show up as 0.5 not 1

---

src/Domain.LinnApps/Reports/PartsReportService.cs

http://pchelpdesk.linn.co.uk/scp/tickets.php?id=17564

add new field to report

---

src/Service.Host/client/src/components/reports/AssemblyFailsDetails.js

Assembly Fails Export Dates

---

src/Service.Host/client/src/components/partFails/PartFail.js

FOR TICKET
